<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

##  User defined functions

print() is an example of an internal function 
you can create your own function! 

### Named functions that return

In [3]:
def greeting(name):
    if name == 'Batman':   #def, the colon and the indentation demarcates the function block
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'
    
print(greeting("Super Man"))

print(greeting(name="Super Man"))

greet=greeting(name='Super Man')
print(greet)

print(greeting(name='Super Man'))

def basic_stats(numbers):
    np_numbers=np.array(numbers)
    return np_numbers.min(), np_numbers.max(), np_numbers.mean()

list_min, list_max, list_mean = basic_stats([1, 2, 3, 4, 5])


Hello Super Man!
Hello Super Man!
Hello Super Man!
Hello Super Man!


### Named functions that don’t return

a function does not have to return anything (like print!)

### Anonymous functions

In [5]:
my_short_function = lambda name: f"Hello {name}!"
my_short_function(name="Super Man")

numbers=[[9, 0, 10],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19]]

sorted(numbers)                         # Sort by comparing the default key 
                                        # (i.e. the 1st element) 
                                        

[[0, 9, 19],
 [1, 8, 18],
 [2, 7, 17],
 [3, 6, 16],
 [4, 5, 15],
 [5, 4, 14],
 [6, 3, 13],
 [7, 2, 12],
 [8, 1, 11],
 [9, 0, 10]]

In [8]:
print(sorted(numbers, key=lambda x: x[1]))     # Sort by comparing a custom key
                                        # that uses the 2nd element
    
print(sorted(numbers, key=lambda x: sum(x)))   # Sort by comparing a custom key
                                        # that uses the sum of the elements

[[9, 0, 10], [8, 1, 11], [7, 2, 12], [6, 3, 13], [5, 4, 14], [4, 5, 15], [3, 6, 16], [2, 7, 17], [1, 8, 18], [0, 9, 19]]
[[9, 0, 10], [8, 1, 11], [7, 2, 12], [6, 3, 13], [5, 4, 14], [4, 5, 15], [3, 6, 16], [2, 7, 17], [1, 8, 18], [0, 9, 19]]


###  Optional arguments

In [9]:
def greeting(name='no one'):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'

greeting()

'Hello no one!'

In [10]:
?print #can accept other argumetns and are optional with default values

## The importance of functions?

### An argument for functions

abstraction of details –> ability to strategise by breaking up complicated solutions into modular chucks (not distracted by unnecesasary information). 

reusability of code –> if you encapsulate a chuck of code in a function, this means your code will be shorter and compact (and copy-paste-able!)

maintainability of code –> with functions, your code is easier to change and maintain because you only need to make changes in one play (at the function definition) 

### A word of caution

however, overloaded functions (i.e. having too many arguments compressed into one function) can increase computational overheads and make your code unreadable. 

## Exercise 1 :  Do you know why?

In [17]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    return f'Hello {name}!'


because return completes the if loop and terminates the run 

## Exercise 2 :  Calculator functions

In [1]:
def add(x,y):
    return(x+y)

def subtract(x,y):
    return(x-y)

def multiply(x,y):
    return(x-y)

def divide(x,y):
    return (x/y)


import numpy as np
x=np.array([36,34,44,76,27])
y=np.array([64,66,56,24,73])

print(add(x,y))
print(subtract(x,y))
print(multiply(x,y))
print(divide(x,y))


[100 100 100 100 100]
[-28 -32 -12  52 -46]
[-28 -32 -12  52 -46]
[0.5625     0.51515152 0.78571429 3.16666667 0.36986301]


## Exercise 3 :  max_info() with NumPy

In [14]:
numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]

def max_info(numbers):
    return (np.max(numbers), np.argmax(numbers))

print(max_info(numbers))


    

(83, 2)
