<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Good)</span></div>

##  Check, balances and contingencies

### assert

In [3]:
x = 10
assert x >= 0, "x is becoming negative!" #the programme will run for as long as the condition is true 

#adding print statements allows the outside world to know what is happening



### try-except

In [7]:
number=input("Give me a number and I will calculate its square.")
square=int(number)**2              # Convert English to number
print(f'The square of {number} is {square}!')

try:
    number=input("Give me a number and I will calculate its square.")
    square=int(number)**2
    print(f'The square of {number} is {square}!')
except:
    print(f"Oh oh! I cannot square {number}!")

Give me a number and I will calculate its square.12
The square of 12 is 144!
Give me a number and I will calculate its square.haha
Oh oh! I cannot square haha!


## Some loose ends

### Positional, keyword and default arguments

In [8]:
def funny_add(a, b, c=1):
    return a + 10*b + 100*c


python cannot unambiguously figure out what the position of 1 is 

### Docstrings

In [10]:
def funny_add(a, b, c=1):
    '''
    A test function to demonstrate how 
    positional, keyword and default arguments 
    work.
    '''
    return a + 10*b + 100*c

help(funny_add)

Help on function funny_add in module __main__:

funny_add(a, b, c=1)
    A test function to demonstrate how 
    positional, keyword and default arguments 
    work.



docstring feature allows us to document what a fucntion does inside the function 

### Function are first class citizens

In [12]:
def my_function(angle, trig_function):
        return trig_function(angle)

# Let's use the function
my_function(np.pi/2, np.sin)        
#> 1.0
my_function(np.pi/2, np.cos)        
#> 6.123233995736766e-17
my_function(np.pi/2, lambda x: np.cos(2*x))  
#> -1.0


-1.0

when we pass a function as an argument, we do not include the parenthesis 

### More unpacking

In [15]:
x, y, z = [1, 2, 3]
print(x, y, z)

x, y, z = np.array([1, 2, 3])
print(x, y, z)

x, *y, z = np.array([1, 2, 3, 4, 5])
print(x, y, z)

x, *_, y = [1, 2, 3, 4, 5]
print(x, y)

1 2 3
1 2 3
1 [2, 3, 4] 5
1 5


## Exercise 1 :  A better calculator I

In [22]:
def add(x, y):
    return x+y


def subtract(x, y):
    return(x-y)


def multiply(x, y):
    return x-y


def divide(x, y):
    return x/y


import numpy as np


x = np.array([36, 34, 44, 76, 27])
y = np.array([64, 66, 56, 24, 73])

assert len(x) != 0, "Array is empty."
assert len(y) != 0, "Array is empty."

print(add(x, y))
print(subtract(x, y))
print(multiply(x, y))
print(divide(x, y))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

## Exercise 2 :  A better calculator II

In [1]:

def add(x, y):
    return x+y


def subtract(x, y):
    return(x-y)


def multiply(x, y):
    return x-y


def divide(x, y):
    return x/y


import numpy as np


x = np.array([36, 34, 44, 76, 27])
y = np.array([64, 66, 56, 24, 73])

try:
    print(add(x, y))
    print(subtract(x, y))
    print(multiply(x, y))
    print(divide(x, y))
except:
    print("Array is empty.") #the bug im trying to solve is that the array is empty 

[100 100 100 100 100]
[-28 -32 -12  52 -46]
[-28 -32 -12  52 -46]
[0.5625     0.51515152 0.78571429 3.16666667 0.36986301]
