<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## Lists, Arrays & Dictionaries

### Let’s compare

In [2]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }


'arrays' refer to NumPy arrays and lsit refer to Python lists 

dictionaries use a key and an assolated valued separeated by a colon :

### Accessing data from a list (or array)

In [7]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

print(py_real_names[0])

print(py_real_names[2])

print(py_super_names[0])

print(py_super_names[2])

Natasha Romanoff
Stephen Strange
Black Widow
Doctor Strange


python is a zeo-indexed langauge, so it starts counting from zero 

you must specify the relevant index starting from zero 

###  Accessing data from a dictionary

In [9]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

print(superhero_info["Natasha Romanoff"])

superhero_info.keys()

superhero_info.values()


Black Widow


dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

###  Higher dimensional lists

In [10]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]


## 2 Lists vs. Arrays

### Size

In [13]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array
        
len(py_list_2d)

len(np_array_2d)

np_array_2d.shape

(10, 2)

### Arrays are fussy about type

In [12]:
py_list = [1, 1.5, 'A']
np.array(py_list)


array(['1', '1.5', 'A'], dtype='<U32')

arrays like having a single data type; lists are more accomodating 

### Adding a number

In [15]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array


np_array + 10

array([11, 12, 13, 14, 15])

### Adding another list

In [19]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

print(py_list_1 + py_list_2)

print(np_array_1 + np_array_2)

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]
[11 22 33 44 55]


###  Multiplying by a Number

In [21]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

print(py_list*2)

print(np_array*2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


multiplying a number makes a lsit grow whereas an arary multiplies its elements by the number

### Squaring

In [23]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

            
np_array**2


array([ 1,  4,  9, 16, 25])

### Asking questions

In [25]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

print(py_list == 3)
print(np_array ==3)
print(np_array >3)


False
[False False  True False False]
[False False False  True  True]


### Mathematics

In [26]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

print(sum(py_list))   # sum() is a base Python function

print(max(py_list))    # max() is a base Python function

print(min(py_list))    # min() is a base Python function

15
5
1


## Exercise 1 :  Total recall?

Q1. both are used for storing data, both are indexed and read from 0 

Q2. arrays can handle arithmetic operations while lists cannot, arrays deal with elements of the same data type while lists can contain elements of different data types

Q3. *dictionaries are used to store data in key:value pairs.*

## Exercise 2 :  Index me

In [27]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]

print(py_list[0])                    # Prints 'a1'
print(py_list[2])                    # Prints 'c3'
print(py_list[4])                    # Prints 'e5'
print(py_list[6])                    # Prints 'g7'
print(py_list[8])                    # Prints 'i9'



a1
c3
e5
g7
i9


## Exercise 3 :  Capitalise Heros

In [30]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

superhero_info['Tony Stark'] = superhero_info['Tony Stark'].upper()  
superhero_info['Natasha Romanoff'] = superhero_info['Natasha Romanoff'].upper()
superhero_info['Stephen Strange'] = superhero_info['Stephen Strange'].upper()

print(superhero_info)


{'Natasha Romanoff': 'BLACK WIDOW', 'Tony Stark': 'IRON MAN', 'Stephen Strange': 'DOCTOR STRANGE'}


## Exercise 4 :  How many ones

In [72]:
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]                  

np_array = np.array(numbers)
np_array == 1
print((np_array==1).sum())







9
